enum traits {
    IGNORE_BLOCKED_ATTACK,
    IGNORE_BLOCKED_MOVE,
    STATIONARY_ATTACK,
    SELF_DESTRUCT,
    REFLECT,
    RADIUS,
    MULTIATTACK,
    STATUS_EFFECT,
    TARGET_ALLY,
    SUMMONER
}

export default traits;